services:
  db:
    image: postgres:13.7-alpine
    container_name: todo-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopassword
      - POSTGRES_DB=tododb
  cache:
    image: redis:6.2.7-alpine
    container_name: todo-cache
    ports:
      - '6379:6379'
